#ifndef MQTTWIFLYWEATHERBOARD_WATCHDOGCONFIG_H_
#define MQTTWIFLYWEATHERBOARD_WATCHDOGCONFIG_H_


#include <avr/wdt.h>

//wdt_enable(WDTO_2S);


#endif  /* MQTTWIFLYWEATHERBOARD_WATCHDOGCONFIG_H_ */

