#ifndef MQTTWIFLYWEATHERBOARD_PROGMEMSTRINGS_H_
#define MQTTWIFLYWEATHERBOARD_PROGMEMSTRINGS_H_


// PROGMEM_STRINGS
const char PROGMEM_STRING_CONNECTED[] PROGMEM = "CONNECTED";
const char PROGMEM_STRING_OK[] PROGMEM = "OK";
const char PROGMEM_STRING_ERROR[] PROGMEM = "ERROR";
const char PROGMEM_STRING_START[] PROGMEM = "START";
const char PROGMEM_STRING_END[] PROGMEM = "END";
const char PROGMEM_STRING_SLEEP[] PROGMEM = "SLEEP";

PGM_P const PROGMEM_STRINGS[] PROGMEM = {
    PROGMEM_STRING_CONNECTED, // idx = 0
    PROGMEM_STRING_OK,        // idx = 1
    PROGMEM_STRING_ERROR,     // idx = 2
    PROGMEM_STRING_START,     // idx = 3
    PROGMEM_STRING_END,       // idx = 4
    PROGMEM_STRING_SLEEP,     // idx = 5
};

/* PROGMEM_STRINGS indices, must match table above */
typedef enum {
  PROGMEM_STRING_CONNECTED_IDX = 0,
  PROGMEM_STRING_OK_IDX = 1,
  PROGMEM_STRING_ERROR_IDX = 2,
  PROGMEM_STRING_START_IDX = 3,
  PROGMEM_STRING_END_IDX = 4,
  PROGMEM_STRING_SLEEP_IDX = 5,
} progmem_strings;


#endif /* MQTTWIFLYWEATHERBOARD_PROGMEMSTRINGS_H_ */
